//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _19_3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class СтудентыEntities : DbContext
    {
        public СтудентыEntities()
            : base("name=СтудентыEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static СтудентыEntities _context;
        public static СтудентыEntities GetContext()
        {
            if (_context == null)
                _context = new СтудентыEntities();
            return _context;
        }
        public virtual DbSet<Авторизация> Авторизация { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
    }
}
